/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AcademicIndexRouteImport } from './routes/academic.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CorporateIndexRouteImport } from './routes/corporate.index'
import { Route as ExamIndexRouteImport } from './routes/exam.index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as PaymentsPaymentIdRouteImport } from './routes/payments.$paymentId'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as AcademicCheckoutOrderIdRouteImport } from './routes/academic.checkout.$orderId'
import { Route as AcademicNotificationsIndexRouteImport } from './routes/academic.notifications.index'
import { Route as AcademicOrdersIndexRouteImport } from './routes/academic.orders.index'
import { Route as AcademicOrdersOrderIdRouteImport } from './routes/academic.orders.$orderId'
import { Route as AcademicPaymentsIndexRouteImport } from './routes/academic.payments.index'
import { Route as AcademicPaymentsPaymentIdRouteImport } from './routes/academic.payments.$paymentId'
import { Route as AcademicProfileIndexRouteImport } from './routes/academic.profile.index'
import { Route as AcademicResourcesIndexRouteImport } from './routes/academic.resources.index'
import { Route as AcademicServicesIndexRouteImport } from './routes/academic.services.index'
import { Route as AcademicServicesProductIdRouteImport } from './routes/academic.services.$productId'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin.payments.index'
import { Route as AdminPaymentsPaymentIdRouteImport } from './routes/admin.payments.$paymentId'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin.requests.index'
import { Route as CorporateCheckoutOrderIdRouteImport } from './routes/corporate.checkout.$orderId'
import { Route as CorporateConsultingIndexRouteImport } from './routes/corporate.consulting.index'
import { Route as CorporateNotificationsIndexRouteImport } from './routes/corporate.notifications.index'
import { Route as CorporateOrdersIndexRouteImport } from './routes/corporate.orders.index'
import { Route as CorporateOrdersOrderIdRouteImport } from './routes/corporate.orders.$orderId'
import { Route as CorporatePaymentsIndexRouteImport } from './routes/corporate.payments.index'
import { Route as CorporatePaymentsPaymentIdRouteImport } from './routes/corporate.payments.$paymentId'
import { Route as CorporateProcurementsIndexRouteImport } from './routes/corporate.procurements.index'
import { Route as CorporateProfileIndexRouteImport } from './routes/corporate.profile.index'
import { Route as CorporateResourcesIndexRouteImport } from './routes/corporate.resources.index'
import { Route as CorporateServicesIndexRouteImport } from './routes/corporate.services.index'
import { Route as CorporateServicesProductIdRouteImport } from './routes/corporate.services.$productId'
import { Route as ExamCheckoutOrderIdRouteImport } from './routes/exam.checkout.$orderId'
import { Route as ExamNotificationsIndexRouteImport } from './routes/exam.notifications.index'
import { Route as ExamOrdersIndexRouteImport } from './routes/exam.orders.index'
import { Route as ExamOrdersOrderIdRouteImport } from './routes/exam.orders.$orderId'
import { Route as ExamPaymentsIndexRouteImport } from './routes/exam.payments.index'
import { Route as ExamPaymentsPaymentIdRouteImport } from './routes/exam.payments.$paymentId'
import { Route as ExamProfileIndexRouteImport } from './routes/exam.profile.index'
import { Route as ExamResourcesIndexRouteImport } from './routes/exam.resources.index'
import { Route as ExamServicesIndexRouteImport } from './routes/exam.services.index'
import { Route as ExamServicesProductIdRouteImport } from './routes/exam.services.$productId'
import { Route as ExamTutoringIndexRouteImport } from './routes/exam.tutoring.index'
import { Route as ExamTutoringRequestIdRouteImport } from './routes/exam.tutoring.$requestId'
import { Route as ExamTutoringNewRouteImport } from './routes/exam.tutoring.new'
import { Route as AdminRequestsConsultingRequestIdRouteImport } from './routes/admin.requests.consulting.$requestId'
import { Route as AdminRequestsProcurementRequestIdRouteImport } from './routes/admin.requests.procurement.$requestId'
import { Route as AdminRequestsTutorRequestIdRouteImport } from './routes/admin.requests.tutor.$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicIndexRoute = AcademicIndexRouteImport.update({
  id: '/academic/',
  path: '/academic/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateIndexRoute = CorporateIndexRouteImport.update({
  id: '/corporate/',
  path: '/corporate/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsPaymentIdRoute = PaymentsPaymentIdRouteImport.update({
  id: '/payments/$paymentId',
  path: '/payments/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicCheckoutOrderIdRoute = AcademicCheckoutOrderIdRouteImport.update({
  id: '/academic/checkout/$orderId',
  path: '/academic/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicNotificationsIndexRoute =
  AcademicNotificationsIndexRouteImport.update({
    id: '/academic/notifications/',
    path: '/academic/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicOrdersIndexRoute = AcademicOrdersIndexRouteImport.update({
  id: '/academic/orders/',
  path: '/academic/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicOrdersOrderIdRoute = AcademicOrdersOrderIdRouteImport.update({
  id: '/academic/orders/$orderId',
  path: '/academic/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicPaymentsIndexRoute = AcademicPaymentsIndexRouteImport.update({
  id: '/academic/payments/',
  path: '/academic/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicPaymentsPaymentIdRoute =
  AcademicPaymentsPaymentIdRouteImport.update({
    id: '/academic/payments/$paymentId',
    path: '/academic/payments/$paymentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicProfileIndexRoute = AcademicProfileIndexRouteImport.update({
  id: '/academic/profile/',
  path: '/academic/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicResourcesIndexRoute = AcademicResourcesIndexRouteImport.update({
  id: '/academic/resources/',
  path: '/academic/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicServicesIndexRoute = AcademicServicesIndexRouteImport.update({
  id: '/academic/services/',
  path: '/academic/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicServicesProductIdRoute =
  AcademicServicesProductIdRouteImport.update({
    id: '/academic/services/$productId',
    path: '/academic/services/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/admin/orders/$orderId',
  path: '/admin/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/admin/payments/',
  path: '/admin/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsPaymentIdRoute = AdminPaymentsPaymentIdRouteImport.update({
  id: '/admin/payments/$paymentId',
  path: '/admin/payments/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/admin/requests/',
  path: '/admin/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateCheckoutOrderIdRoute =
  CorporateCheckoutOrderIdRouteImport.update({
    id: '/corporate/checkout/$orderId',
    path: '/corporate/checkout/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateConsultingIndexRoute =
  CorporateConsultingIndexRouteImport.update({
    id: '/corporate/consulting/',
    path: '/corporate/consulting/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateNotificationsIndexRoute =
  CorporateNotificationsIndexRouteImport.update({
    id: '/corporate/notifications/',
    path: '/corporate/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateOrdersIndexRoute = CorporateOrdersIndexRouteImport.update({
  id: '/corporate/orders/',
  path: '/corporate/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateOrdersOrderIdRoute = CorporateOrdersOrderIdRouteImport.update({
  id: '/corporate/orders/$orderId',
  path: '/corporate/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporatePaymentsIndexRoute = CorporatePaymentsIndexRouteImport.update({
  id: '/corporate/payments/',
  path: '/corporate/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporatePaymentsPaymentIdRoute =
  CorporatePaymentsPaymentIdRouteImport.update({
    id: '/corporate/payments/$paymentId',
    path: '/corporate/payments/$paymentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateProcurementsIndexRoute =
  CorporateProcurementsIndexRouteImport.update({
    id: '/corporate/procurements/',
    path: '/corporate/procurements/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateProfileIndexRoute = CorporateProfileIndexRouteImport.update({
  id: '/corporate/profile/',
  path: '/corporate/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateResourcesIndexRoute = CorporateResourcesIndexRouteImport.update({
  id: '/corporate/resources/',
  path: '/corporate/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateServicesIndexRoute = CorporateServicesIndexRouteImport.update({
  id: '/corporate/services/',
  path: '/corporate/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateServicesProductIdRoute =
  CorporateServicesProductIdRouteImport.update({
    id: '/corporate/services/$productId',
    path: '/corporate/services/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamCheckoutOrderIdRoute = ExamCheckoutOrderIdRouteImport.update({
  id: '/exam/checkout/$orderId',
  path: '/exam/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamNotificationsIndexRoute = ExamNotificationsIndexRouteImport.update({
  id: '/exam/notifications/',
  path: '/exam/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamOrdersIndexRoute = ExamOrdersIndexRouteImport.update({
  id: '/exam/orders/',
  path: '/exam/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamOrdersOrderIdRoute = ExamOrdersOrderIdRouteImport.update({
  id: '/exam/orders/$orderId',
  path: '/exam/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPaymentsIndexRoute = ExamPaymentsIndexRouteImport.update({
  id: '/exam/payments/',
  path: '/exam/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPaymentsPaymentIdRoute = ExamPaymentsPaymentIdRouteImport.update({
  id: '/exam/payments/$paymentId',
  path: '/exam/payments/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamProfileIndexRoute = ExamProfileIndexRouteImport.update({
  id: '/exam/profile/',
  path: '/exam/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamResourcesIndexRoute = ExamResourcesIndexRouteImport.update({
  id: '/exam/resources/',
  path: '/exam/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamServicesIndexRoute = ExamServicesIndexRouteImport.update({
  id: '/exam/services/',
  path: '/exam/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamServicesProductIdRoute = ExamServicesProductIdRouteImport.update({
  id: '/exam/services/$productId',
  path: '/exam/services/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamTutoringIndexRoute = ExamTutoringIndexRouteImport.update({
  id: '/exam/tutoring/',
  path: '/exam/tutoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamTutoringRequestIdRoute = ExamTutoringRequestIdRouteImport.update({
  id: '/exam/tutoring/$requestId',
  path: '/exam/tutoring/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamTutoringNewRoute = ExamTutoringNewRouteImport.update({
  id: '/exam/tutoring/new',
  path: '/exam/tutoring/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsConsultingRequestIdRoute =
  AdminRequestsConsultingRequestIdRouteImport.update({
    id: '/admin/requests/consulting/$requestId',
    path: '/admin/requests/consulting/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRequestsProcurementRequestIdRoute =
  AdminRequestsProcurementRequestIdRouteImport.update({
    id: '/admin/requests/procurement/$requestId',
    path: '/admin/requests/procurement/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRequestsTutorRequestIdRoute =
  AdminRequestsTutorRequestIdRouteImport.update({
    id: '/admin/requests/tutor/$requestId',
    path: '/admin/requests/tutor/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
  '/academic/': typeof AcademicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/corporate/': typeof CorporateIndexRoute
  '/exam/': typeof ExamIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/academic/checkout/$orderId': typeof AcademicCheckoutOrderIdRoute
  '/academic/orders/$orderId': typeof AcademicOrdersOrderIdRoute
  '/academic/payments/$paymentId': typeof AcademicPaymentsPaymentIdRoute
  '/academic/services/$productId': typeof AcademicServicesProductIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/corporate/checkout/$orderId': typeof CorporateCheckoutOrderIdRoute
  '/corporate/orders/$orderId': typeof CorporateOrdersOrderIdRoute
  '/corporate/payments/$paymentId': typeof CorporatePaymentsPaymentIdRoute
  '/corporate/services/$productId': typeof CorporateServicesProductIdRoute
  '/exam/checkout/$orderId': typeof ExamCheckoutOrderIdRoute
  '/exam/orders/$orderId': typeof ExamOrdersOrderIdRoute
  '/exam/payments/$paymentId': typeof ExamPaymentsPaymentIdRoute
  '/exam/services/$productId': typeof ExamServicesProductIdRoute
  '/exam/tutoring/$requestId': typeof ExamTutoringRequestIdRoute
  '/exam/tutoring/new': typeof ExamTutoringNewRoute
  '/academic/notifications/': typeof AcademicNotificationsIndexRoute
  '/academic/orders/': typeof AcademicOrdersIndexRoute
  '/academic/payments/': typeof AcademicPaymentsIndexRoute
  '/academic/profile/': typeof AcademicProfileIndexRoute
  '/academic/resources/': typeof AcademicResourcesIndexRoute
  '/academic/services/': typeof AcademicServicesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/corporate/consulting/': typeof CorporateConsultingIndexRoute
  '/corporate/notifications/': typeof CorporateNotificationsIndexRoute
  '/corporate/orders/': typeof CorporateOrdersIndexRoute
  '/corporate/payments/': typeof CorporatePaymentsIndexRoute
  '/corporate/procurements/': typeof CorporateProcurementsIndexRoute
  '/corporate/profile/': typeof CorporateProfileIndexRoute
  '/corporate/resources/': typeof CorporateResourcesIndexRoute
  '/corporate/services/': typeof CorporateServicesIndexRoute
  '/exam/notifications/': typeof ExamNotificationsIndexRoute
  '/exam/orders/': typeof ExamOrdersIndexRoute
  '/exam/payments/': typeof ExamPaymentsIndexRoute
  '/exam/profile/': typeof ExamProfileIndexRoute
  '/exam/resources/': typeof ExamResourcesIndexRoute
  '/exam/services/': typeof ExamServicesIndexRoute
  '/exam/tutoring/': typeof ExamTutoringIndexRoute
  '/admin/requests/consulting/$requestId': typeof AdminRequestsConsultingRequestIdRoute
  '/admin/requests/procurement/$requestId': typeof AdminRequestsProcurementRequestIdRoute
  '/admin/requests/tutor/$requestId': typeof AdminRequestsTutorRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
  '/academic': typeof AcademicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/corporate': typeof CorporateIndexRoute
  '/exam': typeof ExamIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/academic/checkout/$orderId': typeof AcademicCheckoutOrderIdRoute
  '/academic/orders/$orderId': typeof AcademicOrdersOrderIdRoute
  '/academic/payments/$paymentId': typeof AcademicPaymentsPaymentIdRoute
  '/academic/services/$productId': typeof AcademicServicesProductIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/corporate/checkout/$orderId': typeof CorporateCheckoutOrderIdRoute
  '/corporate/orders/$orderId': typeof CorporateOrdersOrderIdRoute
  '/corporate/payments/$paymentId': typeof CorporatePaymentsPaymentIdRoute
  '/corporate/services/$productId': typeof CorporateServicesProductIdRoute
  '/exam/checkout/$orderId': typeof ExamCheckoutOrderIdRoute
  '/exam/orders/$orderId': typeof ExamOrdersOrderIdRoute
  '/exam/payments/$paymentId': typeof ExamPaymentsPaymentIdRoute
  '/exam/services/$productId': typeof ExamServicesProductIdRoute
  '/exam/tutoring/$requestId': typeof ExamTutoringRequestIdRoute
  '/exam/tutoring/new': typeof ExamTutoringNewRoute
  '/academic/notifications': typeof AcademicNotificationsIndexRoute
  '/academic/orders': typeof AcademicOrdersIndexRoute
  '/academic/payments': typeof AcademicPaymentsIndexRoute
  '/academic/profile': typeof AcademicProfileIndexRoute
  '/academic/resources': typeof AcademicResourcesIndexRoute
  '/academic/services': typeof AcademicServicesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/corporate/consulting': typeof CorporateConsultingIndexRoute
  '/corporate/notifications': typeof CorporateNotificationsIndexRoute
  '/corporate/orders': typeof CorporateOrdersIndexRoute
  '/corporate/payments': typeof CorporatePaymentsIndexRoute
  '/corporate/procurements': typeof CorporateProcurementsIndexRoute
  '/corporate/profile': typeof CorporateProfileIndexRoute
  '/corporate/resources': typeof CorporateResourcesIndexRoute
  '/corporate/services': typeof CorporateServicesIndexRoute
  '/exam/notifications': typeof ExamNotificationsIndexRoute
  '/exam/orders': typeof ExamOrdersIndexRoute
  '/exam/payments': typeof ExamPaymentsIndexRoute
  '/exam/profile': typeof ExamProfileIndexRoute
  '/exam/resources': typeof ExamResourcesIndexRoute
  '/exam/services': typeof ExamServicesIndexRoute
  '/exam/tutoring': typeof ExamTutoringIndexRoute
  '/admin/requests/consulting/$requestId': typeof AdminRequestsConsultingRequestIdRoute
  '/admin/requests/procurement/$requestId': typeof AdminRequestsProcurementRequestIdRoute
  '/admin/requests/tutor/$requestId': typeof AdminRequestsTutorRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
  '/academic/': typeof AcademicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/corporate/': typeof CorporateIndexRoute
  '/exam/': typeof ExamIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/academic/checkout/$orderId': typeof AcademicCheckoutOrderIdRoute
  '/academic/orders/$orderId': typeof AcademicOrdersOrderIdRoute
  '/academic/payments/$paymentId': typeof AcademicPaymentsPaymentIdRoute
  '/academic/services/$productId': typeof AcademicServicesProductIdRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/corporate/checkout/$orderId': typeof CorporateCheckoutOrderIdRoute
  '/corporate/orders/$orderId': typeof CorporateOrdersOrderIdRoute
  '/corporate/payments/$paymentId': typeof CorporatePaymentsPaymentIdRoute
  '/corporate/services/$productId': typeof CorporateServicesProductIdRoute
  '/exam/checkout/$orderId': typeof ExamCheckoutOrderIdRoute
  '/exam/orders/$orderId': typeof ExamOrdersOrderIdRoute
  '/exam/payments/$paymentId': typeof ExamPaymentsPaymentIdRoute
  '/exam/services/$productId': typeof ExamServicesProductIdRoute
  '/exam/tutoring/$requestId': typeof ExamTutoringRequestIdRoute
  '/exam/tutoring/new': typeof ExamTutoringNewRoute
  '/academic/notifications/': typeof AcademicNotificationsIndexRoute
  '/academic/orders/': typeof AcademicOrdersIndexRoute
  '/academic/payments/': typeof AcademicPaymentsIndexRoute
  '/academic/profile/': typeof AcademicProfileIndexRoute
  '/academic/resources/': typeof AcademicResourcesIndexRoute
  '/academic/services/': typeof AcademicServicesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/corporate/consulting/': typeof CorporateConsultingIndexRoute
  '/corporate/notifications/': typeof CorporateNotificationsIndexRoute
  '/corporate/orders/': typeof CorporateOrdersIndexRoute
  '/corporate/payments/': typeof CorporatePaymentsIndexRoute
  '/corporate/procurements/': typeof CorporateProcurementsIndexRoute
  '/corporate/profile/': typeof CorporateProfileIndexRoute
  '/corporate/resources/': typeof CorporateResourcesIndexRoute
  '/corporate/services/': typeof CorporateServicesIndexRoute
  '/exam/notifications/': typeof ExamNotificationsIndexRoute
  '/exam/orders/': typeof ExamOrdersIndexRoute
  '/exam/payments/': typeof ExamPaymentsIndexRoute
  '/exam/profile/': typeof ExamProfileIndexRoute
  '/exam/resources/': typeof ExamResourcesIndexRoute
  '/exam/services/': typeof ExamServicesIndexRoute
  '/exam/tutoring/': typeof ExamTutoringIndexRoute
  '/admin/requests/consulting/$requestId': typeof AdminRequestsConsultingRequestIdRoute
  '/admin/requests/procurement/$requestId': typeof AdminRequestsProcurementRequestIdRoute
  '/admin/requests/tutor/$requestId': typeof AdminRequestsTutorRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/orders/$orderId'
    | '/payments/$paymentId'
    | '/academic/'
    | '/admin/'
    | '/corporate/'
    | '/exam/'
    | '/notifications/'
    | '/orders/'
    | '/payments/'
    | '/profile/'
    | '/resources/'
    | '/academic/checkout/$orderId'
    | '/academic/orders/$orderId'
    | '/academic/payments/$paymentId'
    | '/academic/services/$productId'
    | '/admin/orders/$orderId'
    | '/admin/payments/$paymentId'
    | '/corporate/checkout/$orderId'
    | '/corporate/orders/$orderId'
    | '/corporate/payments/$paymentId'
    | '/corporate/services/$productId'
    | '/exam/checkout/$orderId'
    | '/exam/orders/$orderId'
    | '/exam/payments/$paymentId'
    | '/exam/services/$productId'
    | '/exam/tutoring/$requestId'
    | '/exam/tutoring/new'
    | '/academic/notifications/'
    | '/academic/orders/'
    | '/academic/payments/'
    | '/academic/profile/'
    | '/academic/resources/'
    | '/academic/services/'
    | '/admin/orders/'
    | '/admin/payments/'
    | '/admin/requests/'
    | '/corporate/consulting/'
    | '/corporate/notifications/'
    | '/corporate/orders/'
    | '/corporate/payments/'
    | '/corporate/procurements/'
    | '/corporate/profile/'
    | '/corporate/resources/'
    | '/corporate/services/'
    | '/exam/notifications/'
    | '/exam/orders/'
    | '/exam/payments/'
    | '/exam/profile/'
    | '/exam/resources/'
    | '/exam/services/'
    | '/exam/tutoring/'
    | '/admin/requests/consulting/$requestId'
    | '/admin/requests/procurement/$requestId'
    | '/admin/requests/tutor/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/orders/$orderId'
    | '/payments/$paymentId'
    | '/academic'
    | '/admin'
    | '/corporate'
    | '/exam'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/resources'
    | '/academic/checkout/$orderId'
    | '/academic/orders/$orderId'
    | '/academic/payments/$paymentId'
    | '/academic/services/$productId'
    | '/admin/orders/$orderId'
    | '/admin/payments/$paymentId'
    | '/corporate/checkout/$orderId'
    | '/corporate/orders/$orderId'
    | '/corporate/payments/$paymentId'
    | '/corporate/services/$productId'
    | '/exam/checkout/$orderId'
    | '/exam/orders/$orderId'
    | '/exam/payments/$paymentId'
    | '/exam/services/$productId'
    | '/exam/tutoring/$requestId'
    | '/exam/tutoring/new'
    | '/academic/notifications'
    | '/academic/orders'
    | '/academic/payments'
    | '/academic/profile'
    | '/academic/resources'
    | '/academic/services'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/requests'
    | '/corporate/consulting'
    | '/corporate/notifications'
    | '/corporate/orders'
    | '/corporate/payments'
    | '/corporate/procurements'
    | '/corporate/profile'
    | '/corporate/resources'
    | '/corporate/services'
    | '/exam/notifications'
    | '/exam/orders'
    | '/exam/payments'
    | '/exam/profile'
    | '/exam/resources'
    | '/exam/services'
    | '/exam/tutoring'
    | '/admin/requests/consulting/$requestId'
    | '/admin/requests/procurement/$requestId'
    | '/admin/requests/tutor/$requestId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/orders/$orderId'
    | '/payments/$paymentId'
    | '/academic/'
    | '/admin/'
    | '/corporate/'
    | '/exam/'
    | '/notifications/'
    | '/orders/'
    | '/payments/'
    | '/profile/'
    | '/resources/'
    | '/academic/checkout/$orderId'
    | '/academic/orders/$orderId'
    | '/academic/payments/$paymentId'
    | '/academic/services/$productId'
    | '/admin/orders/$orderId'
    | '/admin/payments/$paymentId'
    | '/corporate/checkout/$orderId'
    | '/corporate/orders/$orderId'
    | '/corporate/payments/$paymentId'
    | '/corporate/services/$productId'
    | '/exam/checkout/$orderId'
    | '/exam/orders/$orderId'
    | '/exam/payments/$paymentId'
    | '/exam/services/$productId'
    | '/exam/tutoring/$requestId'
    | '/exam/tutoring/new'
    | '/academic/notifications/'
    | '/academic/orders/'
    | '/academic/payments/'
    | '/academic/profile/'
    | '/academic/resources/'
    | '/academic/services/'
    | '/admin/orders/'
    | '/admin/payments/'
    | '/admin/requests/'
    | '/corporate/consulting/'
    | '/corporate/notifications/'
    | '/corporate/orders/'
    | '/corporate/payments/'
    | '/corporate/procurements/'
    | '/corporate/profile/'
    | '/corporate/resources/'
    | '/corporate/services/'
    | '/exam/notifications/'
    | '/exam/orders/'
    | '/exam/payments/'
    | '/exam/profile/'
    | '/exam/resources/'
    | '/exam/services/'
    | '/exam/tutoring/'
    | '/admin/requests/consulting/$requestId'
    | '/admin/requests/procurement/$requestId'
    | '/admin/requests/tutor/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  PaymentsPaymentIdRoute: typeof PaymentsPaymentIdRoute
  AcademicIndexRoute: typeof AcademicIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CorporateIndexRoute: typeof CorporateIndexRoute
  ExamIndexRoute: typeof ExamIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  AcademicCheckoutOrderIdRoute: typeof AcademicCheckoutOrderIdRoute
  AcademicOrdersOrderIdRoute: typeof AcademicOrdersOrderIdRoute
  AcademicPaymentsPaymentIdRoute: typeof AcademicPaymentsPaymentIdRoute
  AcademicServicesProductIdRoute: typeof AcademicServicesProductIdRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminPaymentsPaymentIdRoute: typeof AdminPaymentsPaymentIdRoute
  CorporateCheckoutOrderIdRoute: typeof CorporateCheckoutOrderIdRoute
  CorporateOrdersOrderIdRoute: typeof CorporateOrdersOrderIdRoute
  CorporatePaymentsPaymentIdRoute: typeof CorporatePaymentsPaymentIdRoute
  CorporateServicesProductIdRoute: typeof CorporateServicesProductIdRoute
  ExamCheckoutOrderIdRoute: typeof ExamCheckoutOrderIdRoute
  ExamOrdersOrderIdRoute: typeof ExamOrdersOrderIdRoute
  ExamPaymentsPaymentIdRoute: typeof ExamPaymentsPaymentIdRoute
  ExamServicesProductIdRoute: typeof ExamServicesProductIdRoute
  ExamTutoringRequestIdRoute: typeof ExamTutoringRequestIdRoute
  ExamTutoringNewRoute: typeof ExamTutoringNewRoute
  AcademicNotificationsIndexRoute: typeof AcademicNotificationsIndexRoute
  AcademicOrdersIndexRoute: typeof AcademicOrdersIndexRoute
  AcademicPaymentsIndexRoute: typeof AcademicPaymentsIndexRoute
  AcademicProfileIndexRoute: typeof AcademicProfileIndexRoute
  AcademicResourcesIndexRoute: typeof AcademicResourcesIndexRoute
  AcademicServicesIndexRoute: typeof AcademicServicesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
  CorporateConsultingIndexRoute: typeof CorporateConsultingIndexRoute
  CorporateNotificationsIndexRoute: typeof CorporateNotificationsIndexRoute
  CorporateOrdersIndexRoute: typeof CorporateOrdersIndexRoute
  CorporatePaymentsIndexRoute: typeof CorporatePaymentsIndexRoute
  CorporateProcurementsIndexRoute: typeof CorporateProcurementsIndexRoute
  CorporateProfileIndexRoute: typeof CorporateProfileIndexRoute
  CorporateResourcesIndexRoute: typeof CorporateResourcesIndexRoute
  CorporateServicesIndexRoute: typeof CorporateServicesIndexRoute
  ExamNotificationsIndexRoute: typeof ExamNotificationsIndexRoute
  ExamOrdersIndexRoute: typeof ExamOrdersIndexRoute
  ExamPaymentsIndexRoute: typeof ExamPaymentsIndexRoute
  ExamProfileIndexRoute: typeof ExamProfileIndexRoute
  ExamResourcesIndexRoute: typeof ExamResourcesIndexRoute
  ExamServicesIndexRoute: typeof ExamServicesIndexRoute
  ExamTutoringIndexRoute: typeof ExamTutoringIndexRoute
  AdminRequestsConsultingRequestIdRoute: typeof AdminRequestsConsultingRequestIdRoute
  AdminRequestsProcurementRequestIdRoute: typeof AdminRequestsProcurementRequestIdRoute
  AdminRequestsTutorRequestIdRoute: typeof AdminRequestsTutorRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/': {
      id: '/academic/'
      path: '/academic'
      fullPath: '/academic/'
      preLoaderRoute: typeof AcademicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/': {
      id: '/corporate/'
      path: '/corporate'
      fullPath: '/corporate/'
      preLoaderRoute: typeof CorporateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/': {
      id: '/exam/'
      path: '/exam'
      fullPath: '/exam/'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$paymentId': {
      id: '/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/payments/$paymentId'
      preLoaderRoute: typeof PaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/checkout/$orderId': {
      id: '/academic/checkout/$orderId'
      path: '/academic/checkout/$orderId'
      fullPath: '/academic/checkout/$orderId'
      preLoaderRoute: typeof AcademicCheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/notifications/': {
      id: '/academic/notifications/'
      path: '/academic/notifications'
      fullPath: '/academic/notifications/'
      preLoaderRoute: typeof AcademicNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/orders/': {
      id: '/academic/orders/'
      path: '/academic/orders'
      fullPath: '/academic/orders/'
      preLoaderRoute: typeof AcademicOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/orders/$orderId': {
      id: '/academic/orders/$orderId'
      path: '/academic/orders/$orderId'
      fullPath: '/academic/orders/$orderId'
      preLoaderRoute: typeof AcademicOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/payments/': {
      id: '/academic/payments/'
      path: '/academic/payments'
      fullPath: '/academic/payments/'
      preLoaderRoute: typeof AcademicPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/payments/$paymentId': {
      id: '/academic/payments/$paymentId'
      path: '/academic/payments/$paymentId'
      fullPath: '/academic/payments/$paymentId'
      preLoaderRoute: typeof AcademicPaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/profile/': {
      id: '/academic/profile/'
      path: '/academic/profile'
      fullPath: '/academic/profile/'
      preLoaderRoute: typeof AcademicProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/resources/': {
      id: '/academic/resources/'
      path: '/academic/resources'
      fullPath: '/academic/resources/'
      preLoaderRoute: typeof AcademicResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/services/': {
      id: '/academic/services/'
      path: '/academic/services'
      fullPath: '/academic/services/'
      preLoaderRoute: typeof AcademicServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/services/$productId': {
      id: '/academic/services/$productId'
      path: '/academic/services/$productId'
      fullPath: '/academic/services/$productId'
      preLoaderRoute: typeof AcademicServicesProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/admin/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/$paymentId': {
      id: '/admin/payments/$paymentId'
      path: '/admin/payments/$paymentId'
      fullPath: '/admin/payments/$paymentId'
      preLoaderRoute: typeof AdminPaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/admin/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/checkout/$orderId': {
      id: '/corporate/checkout/$orderId'
      path: '/corporate/checkout/$orderId'
      fullPath: '/corporate/checkout/$orderId'
      preLoaderRoute: typeof CorporateCheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/consulting/': {
      id: '/corporate/consulting/'
      path: '/corporate/consulting'
      fullPath: '/corporate/consulting/'
      preLoaderRoute: typeof CorporateConsultingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/notifications/': {
      id: '/corporate/notifications/'
      path: '/corporate/notifications'
      fullPath: '/corporate/notifications/'
      preLoaderRoute: typeof CorporateNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/orders/': {
      id: '/corporate/orders/'
      path: '/corporate/orders'
      fullPath: '/corporate/orders/'
      preLoaderRoute: typeof CorporateOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/orders/$orderId': {
      id: '/corporate/orders/$orderId'
      path: '/corporate/orders/$orderId'
      fullPath: '/corporate/orders/$orderId'
      preLoaderRoute: typeof CorporateOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/payments/': {
      id: '/corporate/payments/'
      path: '/corporate/payments'
      fullPath: '/corporate/payments/'
      preLoaderRoute: typeof CorporatePaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/payments/$paymentId': {
      id: '/corporate/payments/$paymentId'
      path: '/corporate/payments/$paymentId'
      fullPath: '/corporate/payments/$paymentId'
      preLoaderRoute: typeof CorporatePaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/procurements/': {
      id: '/corporate/procurements/'
      path: '/corporate/procurements'
      fullPath: '/corporate/procurements/'
      preLoaderRoute: typeof CorporateProcurementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/profile/': {
      id: '/corporate/profile/'
      path: '/corporate/profile'
      fullPath: '/corporate/profile/'
      preLoaderRoute: typeof CorporateProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/resources/': {
      id: '/corporate/resources/'
      path: '/corporate/resources'
      fullPath: '/corporate/resources/'
      preLoaderRoute: typeof CorporateResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/services/': {
      id: '/corporate/services/'
      path: '/corporate/services'
      fullPath: '/corporate/services/'
      preLoaderRoute: typeof CorporateServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/services/$productId': {
      id: '/corporate/services/$productId'
      path: '/corporate/services/$productId'
      fullPath: '/corporate/services/$productId'
      preLoaderRoute: typeof CorporateServicesProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/checkout/$orderId': {
      id: '/exam/checkout/$orderId'
      path: '/exam/checkout/$orderId'
      fullPath: '/exam/checkout/$orderId'
      preLoaderRoute: typeof ExamCheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/notifications/': {
      id: '/exam/notifications/'
      path: '/exam/notifications'
      fullPath: '/exam/notifications/'
      preLoaderRoute: typeof ExamNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/orders/': {
      id: '/exam/orders/'
      path: '/exam/orders'
      fullPath: '/exam/orders/'
      preLoaderRoute: typeof ExamOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/orders/$orderId': {
      id: '/exam/orders/$orderId'
      path: '/exam/orders/$orderId'
      fullPath: '/exam/orders/$orderId'
      preLoaderRoute: typeof ExamOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/payments/': {
      id: '/exam/payments/'
      path: '/exam/payments'
      fullPath: '/exam/payments/'
      preLoaderRoute: typeof ExamPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/payments/$paymentId': {
      id: '/exam/payments/$paymentId'
      path: '/exam/payments/$paymentId'
      fullPath: '/exam/payments/$paymentId'
      preLoaderRoute: typeof ExamPaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/profile/': {
      id: '/exam/profile/'
      path: '/exam/profile'
      fullPath: '/exam/profile/'
      preLoaderRoute: typeof ExamProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/resources/': {
      id: '/exam/resources/'
      path: '/exam/resources'
      fullPath: '/exam/resources/'
      preLoaderRoute: typeof ExamResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/services/': {
      id: '/exam/services/'
      path: '/exam/services'
      fullPath: '/exam/services/'
      preLoaderRoute: typeof ExamServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/services/$productId': {
      id: '/exam/services/$productId'
      path: '/exam/services/$productId'
      fullPath: '/exam/services/$productId'
      preLoaderRoute: typeof ExamServicesProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/tutoring/': {
      id: '/exam/tutoring/'
      path: '/exam/tutoring'
      fullPath: '/exam/tutoring/'
      preLoaderRoute: typeof ExamTutoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/tutoring/$requestId': {
      id: '/exam/tutoring/$requestId'
      path: '/exam/tutoring/$requestId'
      fullPath: '/exam/tutoring/$requestId'
      preLoaderRoute: typeof ExamTutoringRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/tutoring/new': {
      id: '/exam/tutoring/new'
      path: '/exam/tutoring/new'
      fullPath: '/exam/tutoring/new'
      preLoaderRoute: typeof ExamTutoringNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/consulting/$requestId': {
      id: '/admin/requests/consulting/$requestId'
      path: '/admin/requests/consulting/$requestId'
      fullPath: '/admin/requests/consulting/$requestId'
      preLoaderRoute: typeof AdminRequestsConsultingRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/procurement/$requestId': {
      id: '/admin/requests/procurement/$requestId'
      path: '/admin/requests/procurement/$requestId'
      fullPath: '/admin/requests/procurement/$requestId'
      preLoaderRoute: typeof AdminRequestsProcurementRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/tutor/$requestId': {
      id: '/admin/requests/tutor/$requestId'
      path: '/admin/requests/tutor/$requestId'
      fullPath: '/admin/requests/tutor/$requestId'
      preLoaderRoute: typeof AdminRequestsTutorRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  PaymentsPaymentIdRoute: PaymentsPaymentIdRoute,
  AcademicIndexRoute: AcademicIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  CorporateIndexRoute: CorporateIndexRoute,
  ExamIndexRoute: ExamIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  AcademicCheckoutOrderIdRoute: AcademicCheckoutOrderIdRoute,
  AcademicOrdersOrderIdRoute: AcademicOrdersOrderIdRoute,
  AcademicPaymentsPaymentIdRoute: AcademicPaymentsPaymentIdRoute,
  AcademicServicesProductIdRoute: AcademicServicesProductIdRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminPaymentsPaymentIdRoute: AdminPaymentsPaymentIdRoute,
  CorporateCheckoutOrderIdRoute: CorporateCheckoutOrderIdRoute,
  CorporateOrdersOrderIdRoute: CorporateOrdersOrderIdRoute,
  CorporatePaymentsPaymentIdRoute: CorporatePaymentsPaymentIdRoute,
  CorporateServicesProductIdRoute: CorporateServicesProductIdRoute,
  ExamCheckoutOrderIdRoute: ExamCheckoutOrderIdRoute,
  ExamOrdersOrderIdRoute: ExamOrdersOrderIdRoute,
  ExamPaymentsPaymentIdRoute: ExamPaymentsPaymentIdRoute,
  ExamServicesProductIdRoute: ExamServicesProductIdRoute,
  ExamTutoringRequestIdRoute: ExamTutoringRequestIdRoute,
  ExamTutoringNewRoute: ExamTutoringNewRoute,
  AcademicNotificationsIndexRoute: AcademicNotificationsIndexRoute,
  AcademicOrdersIndexRoute: AcademicOrdersIndexRoute,
  AcademicPaymentsIndexRoute: AcademicPaymentsIndexRoute,
  AcademicProfileIndexRoute: AcademicProfileIndexRoute,
  AcademicResourcesIndexRoute: AcademicResourcesIndexRoute,
  AcademicServicesIndexRoute: AcademicServicesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
  CorporateConsultingIndexRoute: CorporateConsultingIndexRoute,
  CorporateNotificationsIndexRoute: CorporateNotificationsIndexRoute,
  CorporateOrdersIndexRoute: CorporateOrdersIndexRoute,
  CorporatePaymentsIndexRoute: CorporatePaymentsIndexRoute,
  CorporateProcurementsIndexRoute: CorporateProcurementsIndexRoute,
  CorporateProfileIndexRoute: CorporateProfileIndexRoute,
  CorporateResourcesIndexRoute: CorporateResourcesIndexRoute,
  CorporateServicesIndexRoute: CorporateServicesIndexRoute,
  ExamNotificationsIndexRoute: ExamNotificationsIndexRoute,
  ExamOrdersIndexRoute: ExamOrdersIndexRoute,
  ExamPaymentsIndexRoute: ExamPaymentsIndexRoute,
  ExamProfileIndexRoute: ExamProfileIndexRoute,
  ExamResourcesIndexRoute: ExamResourcesIndexRoute,
  ExamServicesIndexRoute: ExamServicesIndexRoute,
  ExamTutoringIndexRoute: ExamTutoringIndexRoute,
  AdminRequestsConsultingRequestIdRoute: AdminRequestsConsultingRequestIdRoute,
  AdminRequestsProcurementRequestIdRoute:
    AdminRequestsProcurementRequestIdRoute,
  AdminRequestsTutorRequestIdRoute: AdminRequestsTutorRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
