/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as AcademicIndexRouteImport } from './routes/academic.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CorporateIndexRouteImport } from './routes/corporate.index'
import { Route as ExamIndexRouteImport } from './routes/exam.index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as PaymentsPaymentIdRouteImport } from './routes/payments.$paymentId'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SupportTicketIdRouteImport } from './routes/support.$ticketId'
import { Route as SupportNewRouteImport } from './routes/support.new'
import { Route as AcademicCheckoutOrderIdRouteImport } from './routes/academic.checkout.$orderId'
import { Route as AcademicNotificationsIndexRouteImport } from './routes/academic.notifications.index'
import { Route as AcademicOrdersIndexRouteImport } from './routes/academic.orders.index'
import { Route as AcademicOrdersOrderIdRouteImport } from './routes/academic.orders.$orderId'
import { Route as AcademicPaymentsIndexRouteImport } from './routes/academic.payments.index'
import { Route as AcademicPaymentsPaymentIdRouteImport } from './routes/academic.payments.$paymentId'
import { Route as AcademicProfileIndexRouteImport } from './routes/academic.profile.index'
import { Route as AcademicResourcesIndexRouteImport } from './routes/academic.resources.index'
import { Route as AcademicServicesIndexRouteImport } from './routes/academic.services.index'
import { Route as AcademicServicesProductIdRouteImport } from './routes/academic.services.$productId'
import { Route as AcademicStoreIndexRouteImport } from './routes/academic.store.index'
import { Route as AcademicStoreProductIdRouteImport } from './routes/academic.store.$productId'
import { Route as AcademicSupportIndexRouteImport } from './routes/academic.support.index'
import { Route as AcademicSupportTicketIdRouteImport } from './routes/academic.support.$ticketId'
import { Route as AcademicSupportNewRouteImport } from './routes/academic.support.new'
import { Route as AdminNotificationsIndexRouteImport } from './routes/admin.notifications.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin.payments.index'
import { Route as AdminPaymentsPaymentIdRouteImport } from './routes/admin.payments.$paymentId'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin.requests.index'
import { Route as AdminResourcesIndexRouteImport } from './routes/admin.resources.index'
import { Route as AdminResourcesResourceIdRouteImport } from './routes/admin.resources.$resourceId'
import { Route as AdminResourcesNewRouteImport } from './routes/admin.resources.new'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin.settings.index'
import { Route as AdminSupportIndexRouteImport } from './routes/admin.support.index'
import { Route as AdminSupportTicketIdRouteImport } from './routes/admin.support.$ticketId'
import { Route as AdminTutorsIndexRouteImport } from './routes/admin.tutors.index'
import { Route as AdminTutorsTutorIdRouteImport } from './routes/admin.tutors.$tutorId'
import { Route as AdminTutorsNewRouteImport } from './routes/admin.tutors.new'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as CorporateCheckoutOrderIdRouteImport } from './routes/corporate.checkout.$orderId'
import { Route as CorporateConsultingIndexRouteImport } from './routes/corporate.consulting.index'
import { Route as CorporateNotificationsIndexRouteImport } from './routes/corporate.notifications.index'
import { Route as CorporateOrdersIndexRouteImport } from './routes/corporate.orders.index'
import { Route as CorporateOrdersOrderIdRouteImport } from './routes/corporate.orders.$orderId'
import { Route as CorporatePaymentsIndexRouteImport } from './routes/corporate.payments.index'
import { Route as CorporatePaymentsPaymentIdRouteImport } from './routes/corporate.payments.$paymentId'
import { Route as CorporateProcurementsIndexRouteImport } from './routes/corporate.procurements.index'
import { Route as CorporateProfileIndexRouteImport } from './routes/corporate.profile.index'
import { Route as CorporateResourcesIndexRouteImport } from './routes/corporate.resources.index'
import { Route as CorporateServicesIndexRouteImport } from './routes/corporate.services.index'
import { Route as CorporateServicesProductIdRouteImport } from './routes/corporate.services.$productId'
import { Route as CorporateStoreIndexRouteImport } from './routes/corporate.store.index'
import { Route as CorporateStoreProductIdRouteImport } from './routes/corporate.store.$productId'
import { Route as CorporateSupportIndexRouteImport } from './routes/corporate.support.index'
import { Route as CorporateSupportTicketIdRouteImport } from './routes/corporate.support.$ticketId'
import { Route as CorporateSupportNewRouteImport } from './routes/corporate.support.new'
import { Route as ExamCheckoutOrderIdRouteImport } from './routes/exam.checkout.$orderId'
import { Route as ExamNotificationsIndexRouteImport } from './routes/exam.notifications.index'
import { Route as ExamOrdersIndexRouteImport } from './routes/exam.orders.index'
import { Route as ExamOrdersOrderIdRouteImport } from './routes/exam.orders.$orderId'
import { Route as ExamPaymentsIndexRouteImport } from './routes/exam.payments.index'
import { Route as ExamPaymentsPaymentIdRouteImport } from './routes/exam.payments.$paymentId'
import { Route as ExamProfileIndexRouteImport } from './routes/exam.profile.index'
import { Route as ExamResourcesIndexRouteImport } from './routes/exam.resources.index'
import { Route as ExamServicesIndexRouteImport } from './routes/exam.services.index'
import { Route as ExamServicesProductIdRouteImport } from './routes/exam.services.$productId'
import { Route as ExamStoreIndexRouteImport } from './routes/exam.store.index'
import { Route as ExamStoreProductIdRouteImport } from './routes/exam.store.$productId'
import { Route as ExamSupportIndexRouteImport } from './routes/exam.support.index'
import { Route as ExamSupportTicketIdRouteImport } from './routes/exam.support.$ticketId'
import { Route as ExamSupportNewRouteImport } from './routes/exam.support.new'
import { Route as ExamTutoringIndexRouteImport } from './routes/exam.tutoring.index'
import { Route as ExamTutoringRequestIdRouteImport } from './routes/exam.tutoring.$requestId'
import { Route as ExamTutoringNewRouteImport } from './routes/exam.tutoring.new'
import { Route as AdminRequestsConsultingRequestIdRouteImport } from './routes/admin.requests.consulting.$requestId'
import { Route as AdminRequestsProcurementRequestIdRouteImport } from './routes/admin.requests.procurement.$requestId'
import { Route as AdminRequestsTutorRequestIdRouteImport } from './routes/admin.requests.tutor.$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicIndexRoute = AcademicIndexRouteImport.update({
  id: '/academic/',
  path: '/academic/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateIndexRoute = CorporateIndexRouteImport.update({
  id: '/corporate/',
  path: '/corporate/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsPaymentIdRoute = PaymentsPaymentIdRouteImport.update({
  id: '/payments/$paymentId',
  path: '/payments/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTicketIdRoute = SupportTicketIdRouteImport.update({
  id: '/support/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportNewRoute = SupportNewRouteImport.update({
  id: '/support/new',
  path: '/support/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicCheckoutOrderIdRoute = AcademicCheckoutOrderIdRouteImport.update({
  id: '/academic/checkout/$orderId',
  path: '/academic/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicNotificationsIndexRoute =
  AcademicNotificationsIndexRouteImport.update({
    id: '/academic/notifications/',
    path: '/academic/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicOrdersIndexRoute = AcademicOrdersIndexRouteImport.update({
  id: '/academic/orders/',
  path: '/academic/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicOrdersOrderIdRoute = AcademicOrdersOrderIdRouteImport.update({
  id: '/academic/orders/$orderId',
  path: '/academic/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicPaymentsIndexRoute = AcademicPaymentsIndexRouteImport.update({
  id: '/academic/payments/',
  path: '/academic/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicPaymentsPaymentIdRoute =
  AcademicPaymentsPaymentIdRouteImport.update({
    id: '/academic/payments/$paymentId',
    path: '/academic/payments/$paymentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicProfileIndexRoute = AcademicProfileIndexRouteImport.update({
  id: '/academic/profile/',
  path: '/academic/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicResourcesIndexRoute = AcademicResourcesIndexRouteImport.update({
  id: '/academic/resources/',
  path: '/academic/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicServicesIndexRoute = AcademicServicesIndexRouteImport.update({
  id: '/academic/services/',
  path: '/academic/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicServicesProductIdRoute =
  AcademicServicesProductIdRouteImport.update({
    id: '/academic/services/$productId',
    path: '/academic/services/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicStoreIndexRoute = AcademicStoreIndexRouteImport.update({
  id: '/academic/store/',
  path: '/academic/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicStoreProductIdRoute = AcademicStoreProductIdRouteImport.update({
  id: '/academic/store/$productId',
  path: '/academic/store/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicSupportIndexRoute = AcademicSupportIndexRouteImport.update({
  id: '/academic/support/',
  path: '/academic/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicSupportTicketIdRoute = AcademicSupportTicketIdRouteImport.update({
  id: '/academic/support/$ticketId',
  path: '/academic/support/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicSupportNewRoute = AcademicSupportNewRouteImport.update({
  id: '/academic/support/new',
  path: '/academic/support/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsIndexRoute = AdminNotificationsIndexRouteImport.update({
  id: '/admin/notifications/',
  path: '/admin/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/admin/orders/$orderId',
  path: '/admin/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/admin/payments/',
  path: '/admin/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsPaymentIdRoute = AdminPaymentsPaymentIdRouteImport.update({
  id: '/admin/payments/$paymentId',
  path: '/admin/payments/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/admin/requests/',
  path: '/admin/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResourcesIndexRoute = AdminResourcesIndexRouteImport.update({
  id: '/admin/resources/',
  path: '/admin/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResourcesResourceIdRoute =
  AdminResourcesResourceIdRouteImport.update({
    id: '/admin/resources/$resourceId',
    path: '/admin/resources/$resourceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminResourcesNewRoute = AdminResourcesNewRouteImport.update({
  id: '/admin/resources/new',
  path: '/admin/resources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportIndexRoute = AdminSupportIndexRouteImport.update({
  id: '/admin/support/',
  path: '/admin/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportTicketIdRoute = AdminSupportTicketIdRouteImport.update({
  id: '/admin/support/$ticketId',
  path: '/admin/support/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTutorsIndexRoute = AdminTutorsIndexRouteImport.update({
  id: '/admin/tutors/',
  path: '/admin/tutors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTutorsTutorIdRoute = AdminTutorsTutorIdRouteImport.update({
  id: '/admin/tutors/$tutorId',
  path: '/admin/tutors/$tutorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTutorsNewRoute = AdminTutorsNewRouteImport.update({
  id: '/admin/tutors/new',
  path: '/admin/tutors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateCheckoutOrderIdRoute =
  CorporateCheckoutOrderIdRouteImport.update({
    id: '/corporate/checkout/$orderId',
    path: '/corporate/checkout/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateConsultingIndexRoute =
  CorporateConsultingIndexRouteImport.update({
    id: '/corporate/consulting/',
    path: '/corporate/consulting/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateNotificationsIndexRoute =
  CorporateNotificationsIndexRouteImport.update({
    id: '/corporate/notifications/',
    path: '/corporate/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateOrdersIndexRoute = CorporateOrdersIndexRouteImport.update({
  id: '/corporate/orders/',
  path: '/corporate/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateOrdersOrderIdRoute = CorporateOrdersOrderIdRouteImport.update({
  id: '/corporate/orders/$orderId',
  path: '/corporate/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporatePaymentsIndexRoute = CorporatePaymentsIndexRouteImport.update({
  id: '/corporate/payments/',
  path: '/corporate/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporatePaymentsPaymentIdRoute =
  CorporatePaymentsPaymentIdRouteImport.update({
    id: '/corporate/payments/$paymentId',
    path: '/corporate/payments/$paymentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateProcurementsIndexRoute =
  CorporateProcurementsIndexRouteImport.update({
    id: '/corporate/procurements/',
    path: '/corporate/procurements/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateProfileIndexRoute = CorporateProfileIndexRouteImport.update({
  id: '/corporate/profile/',
  path: '/corporate/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateResourcesIndexRoute = CorporateResourcesIndexRouteImport.update({
  id: '/corporate/resources/',
  path: '/corporate/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateServicesIndexRoute = CorporateServicesIndexRouteImport.update({
  id: '/corporate/services/',
  path: '/corporate/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateServicesProductIdRoute =
  CorporateServicesProductIdRouteImport.update({
    id: '/corporate/services/$productId',
    path: '/corporate/services/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateStoreIndexRoute = CorporateStoreIndexRouteImport.update({
  id: '/corporate/store/',
  path: '/corporate/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateStoreProductIdRoute = CorporateStoreProductIdRouteImport.update({
  id: '/corporate/store/$productId',
  path: '/corporate/store/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateSupportIndexRoute = CorporateSupportIndexRouteImport.update({
  id: '/corporate/support/',
  path: '/corporate/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateSupportTicketIdRoute =
  CorporateSupportTicketIdRouteImport.update({
    id: '/corporate/support/$ticketId',
    path: '/corporate/support/$ticketId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorporateSupportNewRoute = CorporateSupportNewRouteImport.update({
  id: '/corporate/support/new',
  path: '/corporate/support/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamCheckoutOrderIdRoute = ExamCheckoutOrderIdRouteImport.update({
  id: '/exam/checkout/$orderId',
  path: '/exam/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamNotificationsIndexRoute = ExamNotificationsIndexRouteImport.update({
  id: '/exam/notifications/',
  path: '/exam/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamOrdersIndexRoute = ExamOrdersIndexRouteImport.update({
  id: '/exam/orders/',
  path: '/exam/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamOrdersOrderIdRoute = ExamOrdersOrderIdRouteImport.update({
  id: '/exam/orders/$orderId',
  path: '/exam/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPaymentsIndexRoute = ExamPaymentsIndexRouteImport.update({
  id: '/exam/payments/',
  path: '/exam/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPaymentsPaymentIdRoute = ExamPaymentsPaymentIdRouteImport.update({
  id: '/exam/payments/$paymentId',
  path: '/exam/payments/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamProfileIndexRoute = ExamProfileIndexRouteImport.update({
  id: '/exam/profile/',
  path: '/exam/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamResourcesIndexRoute = ExamResourcesIndexRouteImport.update({
  id: '/exam/resources/',
  path: '/exam/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamServicesIndexRoute = ExamServicesIndexRouteImport.update({
  id: '/exam/services/',
  path: '/exam/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamServicesProductIdRoute = ExamServicesProductIdRouteImport.update({
  id: '/exam/services/$productId',
  path: '/exam/services/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamStoreIndexRoute = ExamStoreIndexRouteImport.update({
  id: '/exam/store/',
  path: '/exam/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamStoreProductIdRoute = ExamStoreProductIdRouteImport.update({
  id: '/exam/store/$productId',
  path: '/exam/store/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSupportIndexRoute = ExamSupportIndexRouteImport.update({
  id: '/exam/support/',
  path: '/exam/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSupportTicketIdRoute = ExamSupportTicketIdRouteImport.update({
  id: '/exam/support/$ticketId',
  path: '/exam/support/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSupportNewRoute = ExamSupportNewRouteImport.update({
  id: '/exam/support/new',
  path: '/exam/support/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamTutoringIndexRoute = ExamTutoringIndexRouteImport.update({
  id: '/exam/tutoring/',
  path: '/exam/tutoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamTutoringRequestIdRoute = ExamTutoringRequestIdRouteImport.update({
  id: '/exam/tutoring/$requestId',
  path: '/exam/tutoring/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamTutoringNewRoute = ExamTutoringNewRouteImport.update({
  id: '/exam/tutoring/new',
  path: '/exam/tutoring/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsConsultingRequestIdRoute =
  AdminRequestsConsultingRequestIdRouteImport.update({
    id: '/admin/requests/consulting/$requestId',
    path: '/admin/requests/consulting/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRequestsProcurementRequestIdRoute =
  AdminRequestsProcurementRequestIdRouteImport.update({
    id: '/admin/requests/procurement/$requestId',
    path: '/admin/requests/procurement/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRequestsTutorRequestIdRoute =
  AdminRequestsTutorRequestIdRouteImport.update({
    id: '/admin/requests/tutor/$requestId',
    path: '/admin/requests/tutor/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/support/new': typeof SupportNewRoute
  '/academic/': typeof AcademicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/corporate/': typeof CorporateIndexRoute
  '/exam/': typeof ExamIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/support/': typeof SupportIndexRoute
  '/academic/checkout/$orderId': typeof AcademicCheckoutOrderIdRoute
  '/academic/orders/$orderId': typeof AcademicOrdersOrderIdRoute
  '/academic/payments/$paymentId': typeof AcademicPaymentsPaymentIdRoute
  '/academic/services/$productId': typeof AcademicServicesProductIdRoute
  '/academic/store/$productId': typeof AcademicStoreProductIdRoute
  '/academic/support/$ticketId': typeof AcademicSupportTicketIdRoute
  '/academic/support/new': typeof AcademicSupportNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/admin/resources/$resourceId': typeof AdminResourcesResourceIdRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/admin/tutors/$tutorId': typeof AdminTutorsTutorIdRoute
  '/admin/tutors/new': typeof AdminTutorsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/corporate/checkout/$orderId': typeof CorporateCheckoutOrderIdRoute
  '/corporate/orders/$orderId': typeof CorporateOrdersOrderIdRoute
  '/corporate/payments/$paymentId': typeof CorporatePaymentsPaymentIdRoute
  '/corporate/services/$productId': typeof CorporateServicesProductIdRoute
  '/corporate/store/$productId': typeof CorporateStoreProductIdRoute
  '/corporate/support/$ticketId': typeof CorporateSupportTicketIdRoute
  '/corporate/support/new': typeof CorporateSupportNewRoute
  '/exam/checkout/$orderId': typeof ExamCheckoutOrderIdRoute
  '/exam/orders/$orderId': typeof ExamOrdersOrderIdRoute
  '/exam/payments/$paymentId': typeof ExamPaymentsPaymentIdRoute
  '/exam/services/$productId': typeof ExamServicesProductIdRoute
  '/exam/store/$productId': typeof ExamStoreProductIdRoute
  '/exam/support/$ticketId': typeof ExamSupportTicketIdRoute
  '/exam/support/new': typeof ExamSupportNewRoute
  '/exam/tutoring/$requestId': typeof ExamTutoringRequestIdRoute
  '/exam/tutoring/new': typeof ExamTutoringNewRoute
  '/academic/notifications/': typeof AcademicNotificationsIndexRoute
  '/academic/orders/': typeof AcademicOrdersIndexRoute
  '/academic/payments/': typeof AcademicPaymentsIndexRoute
  '/academic/profile/': typeof AcademicProfileIndexRoute
  '/academic/resources/': typeof AcademicResourcesIndexRoute
  '/academic/services/': typeof AcademicServicesIndexRoute
  '/academic/store/': typeof AcademicStoreIndexRoute
  '/academic/support/': typeof AcademicSupportIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
  '/admin/tutors/': typeof AdminTutorsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/corporate/consulting/': typeof CorporateConsultingIndexRoute
  '/corporate/notifications/': typeof CorporateNotificationsIndexRoute
  '/corporate/orders/': typeof CorporateOrdersIndexRoute
  '/corporate/payments/': typeof CorporatePaymentsIndexRoute
  '/corporate/procurements/': typeof CorporateProcurementsIndexRoute
  '/corporate/profile/': typeof CorporateProfileIndexRoute
  '/corporate/resources/': typeof CorporateResourcesIndexRoute
  '/corporate/services/': typeof CorporateServicesIndexRoute
  '/corporate/store/': typeof CorporateStoreIndexRoute
  '/corporate/support/': typeof CorporateSupportIndexRoute
  '/exam/notifications/': typeof ExamNotificationsIndexRoute
  '/exam/orders/': typeof ExamOrdersIndexRoute
  '/exam/payments/': typeof ExamPaymentsIndexRoute
  '/exam/profile/': typeof ExamProfileIndexRoute
  '/exam/resources/': typeof ExamResourcesIndexRoute
  '/exam/services/': typeof ExamServicesIndexRoute
  '/exam/store/': typeof ExamStoreIndexRoute
  '/exam/support/': typeof ExamSupportIndexRoute
  '/exam/tutoring/': typeof ExamTutoringIndexRoute
  '/admin/requests/consulting/$requestId': typeof AdminRequestsConsultingRequestIdRoute
  '/admin/requests/procurement/$requestId': typeof AdminRequestsProcurementRequestIdRoute
  '/admin/requests/tutor/$requestId': typeof AdminRequestsTutorRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/support/new': typeof SupportNewRoute
  '/academic': typeof AcademicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/corporate': typeof CorporateIndexRoute
  '/exam': typeof ExamIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/support': typeof SupportIndexRoute
  '/academic/checkout/$orderId': typeof AcademicCheckoutOrderIdRoute
  '/academic/orders/$orderId': typeof AcademicOrdersOrderIdRoute
  '/academic/payments/$paymentId': typeof AcademicPaymentsPaymentIdRoute
  '/academic/services/$productId': typeof AcademicServicesProductIdRoute
  '/academic/store/$productId': typeof AcademicStoreProductIdRoute
  '/academic/support/$ticketId': typeof AcademicSupportTicketIdRoute
  '/academic/support/new': typeof AcademicSupportNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/admin/resources/$resourceId': typeof AdminResourcesResourceIdRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/admin/tutors/$tutorId': typeof AdminTutorsTutorIdRoute
  '/admin/tutors/new': typeof AdminTutorsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/corporate/checkout/$orderId': typeof CorporateCheckoutOrderIdRoute
  '/corporate/orders/$orderId': typeof CorporateOrdersOrderIdRoute
  '/corporate/payments/$paymentId': typeof CorporatePaymentsPaymentIdRoute
  '/corporate/services/$productId': typeof CorporateServicesProductIdRoute
  '/corporate/store/$productId': typeof CorporateStoreProductIdRoute
  '/corporate/support/$ticketId': typeof CorporateSupportTicketIdRoute
  '/corporate/support/new': typeof CorporateSupportNewRoute
  '/exam/checkout/$orderId': typeof ExamCheckoutOrderIdRoute
  '/exam/orders/$orderId': typeof ExamOrdersOrderIdRoute
  '/exam/payments/$paymentId': typeof ExamPaymentsPaymentIdRoute
  '/exam/services/$productId': typeof ExamServicesProductIdRoute
  '/exam/store/$productId': typeof ExamStoreProductIdRoute
  '/exam/support/$ticketId': typeof ExamSupportTicketIdRoute
  '/exam/support/new': typeof ExamSupportNewRoute
  '/exam/tutoring/$requestId': typeof ExamTutoringRequestIdRoute
  '/exam/tutoring/new': typeof ExamTutoringNewRoute
  '/academic/notifications': typeof AcademicNotificationsIndexRoute
  '/academic/orders': typeof AcademicOrdersIndexRoute
  '/academic/payments': typeof AcademicPaymentsIndexRoute
  '/academic/profile': typeof AcademicProfileIndexRoute
  '/academic/resources': typeof AcademicResourcesIndexRoute
  '/academic/services': typeof AcademicServicesIndexRoute
  '/academic/store': typeof AcademicStoreIndexRoute
  '/academic/support': typeof AcademicSupportIndexRoute
  '/admin/notifications': typeof AdminNotificationsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/admin/resources': typeof AdminResourcesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/support': typeof AdminSupportIndexRoute
  '/admin/tutors': typeof AdminTutorsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/corporate/consulting': typeof CorporateConsultingIndexRoute
  '/corporate/notifications': typeof CorporateNotificationsIndexRoute
  '/corporate/orders': typeof CorporateOrdersIndexRoute
  '/corporate/payments': typeof CorporatePaymentsIndexRoute
  '/corporate/procurements': typeof CorporateProcurementsIndexRoute
  '/corporate/profile': typeof CorporateProfileIndexRoute
  '/corporate/resources': typeof CorporateResourcesIndexRoute
  '/corporate/services': typeof CorporateServicesIndexRoute
  '/corporate/store': typeof CorporateStoreIndexRoute
  '/corporate/support': typeof CorporateSupportIndexRoute
  '/exam/notifications': typeof ExamNotificationsIndexRoute
  '/exam/orders': typeof ExamOrdersIndexRoute
  '/exam/payments': typeof ExamPaymentsIndexRoute
  '/exam/profile': typeof ExamProfileIndexRoute
  '/exam/resources': typeof ExamResourcesIndexRoute
  '/exam/services': typeof ExamServicesIndexRoute
  '/exam/store': typeof ExamStoreIndexRoute
  '/exam/support': typeof ExamSupportIndexRoute
  '/exam/tutoring': typeof ExamTutoringIndexRoute
  '/admin/requests/consulting/$requestId': typeof AdminRequestsConsultingRequestIdRoute
  '/admin/requests/procurement/$requestId': typeof AdminRequestsProcurementRequestIdRoute
  '/admin/requests/tutor/$requestId': typeof AdminRequestsTutorRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/support/new': typeof SupportNewRoute
  '/academic/': typeof AcademicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/corporate/': typeof CorporateIndexRoute
  '/exam/': typeof ExamIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/support/': typeof SupportIndexRoute
  '/academic/checkout/$orderId': typeof AcademicCheckoutOrderIdRoute
  '/academic/orders/$orderId': typeof AcademicOrdersOrderIdRoute
  '/academic/payments/$paymentId': typeof AcademicPaymentsPaymentIdRoute
  '/academic/services/$productId': typeof AcademicServicesProductIdRoute
  '/academic/store/$productId': typeof AcademicStoreProductIdRoute
  '/academic/support/$ticketId': typeof AcademicSupportTicketIdRoute
  '/academic/support/new': typeof AcademicSupportNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/admin/resources/$resourceId': typeof AdminResourcesResourceIdRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/admin/tutors/$tutorId': typeof AdminTutorsTutorIdRoute
  '/admin/tutors/new': typeof AdminTutorsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/corporate/checkout/$orderId': typeof CorporateCheckoutOrderIdRoute
  '/corporate/orders/$orderId': typeof CorporateOrdersOrderIdRoute
  '/corporate/payments/$paymentId': typeof CorporatePaymentsPaymentIdRoute
  '/corporate/services/$productId': typeof CorporateServicesProductIdRoute
  '/corporate/store/$productId': typeof CorporateStoreProductIdRoute
  '/corporate/support/$ticketId': typeof CorporateSupportTicketIdRoute
  '/corporate/support/new': typeof CorporateSupportNewRoute
  '/exam/checkout/$orderId': typeof ExamCheckoutOrderIdRoute
  '/exam/orders/$orderId': typeof ExamOrdersOrderIdRoute
  '/exam/payments/$paymentId': typeof ExamPaymentsPaymentIdRoute
  '/exam/services/$productId': typeof ExamServicesProductIdRoute
  '/exam/store/$productId': typeof ExamStoreProductIdRoute
  '/exam/support/$ticketId': typeof ExamSupportTicketIdRoute
  '/exam/support/new': typeof ExamSupportNewRoute
  '/exam/tutoring/$requestId': typeof ExamTutoringRequestIdRoute
  '/exam/tutoring/new': typeof ExamTutoringNewRoute
  '/academic/notifications/': typeof AcademicNotificationsIndexRoute
  '/academic/orders/': typeof AcademicOrdersIndexRoute
  '/academic/payments/': typeof AcademicPaymentsIndexRoute
  '/academic/profile/': typeof AcademicProfileIndexRoute
  '/academic/resources/': typeof AcademicResourcesIndexRoute
  '/academic/services/': typeof AcademicServicesIndexRoute
  '/academic/store/': typeof AcademicStoreIndexRoute
  '/academic/support/': typeof AcademicSupportIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
  '/admin/tutors/': typeof AdminTutorsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/corporate/consulting/': typeof CorporateConsultingIndexRoute
  '/corporate/notifications/': typeof CorporateNotificationsIndexRoute
  '/corporate/orders/': typeof CorporateOrdersIndexRoute
  '/corporate/payments/': typeof CorporatePaymentsIndexRoute
  '/corporate/procurements/': typeof CorporateProcurementsIndexRoute
  '/corporate/profile/': typeof CorporateProfileIndexRoute
  '/corporate/resources/': typeof CorporateResourcesIndexRoute
  '/corporate/services/': typeof CorporateServicesIndexRoute
  '/corporate/store/': typeof CorporateStoreIndexRoute
  '/corporate/support/': typeof CorporateSupportIndexRoute
  '/exam/notifications/': typeof ExamNotificationsIndexRoute
  '/exam/orders/': typeof ExamOrdersIndexRoute
  '/exam/payments/': typeof ExamPaymentsIndexRoute
  '/exam/profile/': typeof ExamProfileIndexRoute
  '/exam/resources/': typeof ExamResourcesIndexRoute
  '/exam/services/': typeof ExamServicesIndexRoute
  '/exam/store/': typeof ExamStoreIndexRoute
  '/exam/support/': typeof ExamSupportIndexRoute
  '/exam/tutoring/': typeof ExamTutoringIndexRoute
  '/admin/requests/consulting/$requestId': typeof AdminRequestsConsultingRequestIdRoute
  '/admin/requests/procurement/$requestId': typeof AdminRequestsProcurementRequestIdRoute
  '/admin/requests/tutor/$requestId': typeof AdminRequestsTutorRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/reset-password'
    | '/terms-of-service'
    | '/orders/$orderId'
    | '/payments/$paymentId'
    | '/support/$ticketId'
    | '/support/new'
    | '/academic/'
    | '/admin/'
    | '/corporate/'
    | '/exam/'
    | '/notifications/'
    | '/orders/'
    | '/payments/'
    | '/profile/'
    | '/resources/'
    | '/support/'
    | '/academic/checkout/$orderId'
    | '/academic/orders/$orderId'
    | '/academic/payments/$paymentId'
    | '/academic/services/$productId'
    | '/academic/store/$productId'
    | '/academic/support/$ticketId'
    | '/academic/support/new'
    | '/admin/orders/$orderId'
    | '/admin/payments/$paymentId'
    | '/admin/resources/$resourceId'
    | '/admin/resources/new'
    | '/admin/support/$ticketId'
    | '/admin/tutors/$tutorId'
    | '/admin/tutors/new'
    | '/admin/users/$userId'
    | '/corporate/checkout/$orderId'
    | '/corporate/orders/$orderId'
    | '/corporate/payments/$paymentId'
    | '/corporate/services/$productId'
    | '/corporate/store/$productId'
    | '/corporate/support/$ticketId'
    | '/corporate/support/new'
    | '/exam/checkout/$orderId'
    | '/exam/orders/$orderId'
    | '/exam/payments/$paymentId'
    | '/exam/services/$productId'
    | '/exam/store/$productId'
    | '/exam/support/$ticketId'
    | '/exam/support/new'
    | '/exam/tutoring/$requestId'
    | '/exam/tutoring/new'
    | '/academic/notifications/'
    | '/academic/orders/'
    | '/academic/payments/'
    | '/academic/profile/'
    | '/academic/resources/'
    | '/academic/services/'
    | '/academic/store/'
    | '/academic/support/'
    | '/admin/notifications/'
    | '/admin/orders/'
    | '/admin/payments/'
    | '/admin/requests/'
    | '/admin/resources/'
    | '/admin/settings/'
    | '/admin/support/'
    | '/admin/tutors/'
    | '/admin/users/'
    | '/corporate/consulting/'
    | '/corporate/notifications/'
    | '/corporate/orders/'
    | '/corporate/payments/'
    | '/corporate/procurements/'
    | '/corporate/profile/'
    | '/corporate/resources/'
    | '/corporate/services/'
    | '/corporate/store/'
    | '/corporate/support/'
    | '/exam/notifications/'
    | '/exam/orders/'
    | '/exam/payments/'
    | '/exam/profile/'
    | '/exam/resources/'
    | '/exam/services/'
    | '/exam/store/'
    | '/exam/support/'
    | '/exam/tutoring/'
    | '/admin/requests/consulting/$requestId'
    | '/admin/requests/procurement/$requestId'
    | '/admin/requests/tutor/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/reset-password'
    | '/terms-of-service'
    | '/orders/$orderId'
    | '/payments/$paymentId'
    | '/support/$ticketId'
    | '/support/new'
    | '/academic'
    | '/admin'
    | '/corporate'
    | '/exam'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/resources'
    | '/support'
    | '/academic/checkout/$orderId'
    | '/academic/orders/$orderId'
    | '/academic/payments/$paymentId'
    | '/academic/services/$productId'
    | '/academic/store/$productId'
    | '/academic/support/$ticketId'
    | '/academic/support/new'
    | '/admin/orders/$orderId'
    | '/admin/payments/$paymentId'
    | '/admin/resources/$resourceId'
    | '/admin/resources/new'
    | '/admin/support/$ticketId'
    | '/admin/tutors/$tutorId'
    | '/admin/tutors/new'
    | '/admin/users/$userId'
    | '/corporate/checkout/$orderId'
    | '/corporate/orders/$orderId'
    | '/corporate/payments/$paymentId'
    | '/corporate/services/$productId'
    | '/corporate/store/$productId'
    | '/corporate/support/$ticketId'
    | '/corporate/support/new'
    | '/exam/checkout/$orderId'
    | '/exam/orders/$orderId'
    | '/exam/payments/$paymentId'
    | '/exam/services/$productId'
    | '/exam/store/$productId'
    | '/exam/support/$ticketId'
    | '/exam/support/new'
    | '/exam/tutoring/$requestId'
    | '/exam/tutoring/new'
    | '/academic/notifications'
    | '/academic/orders'
    | '/academic/payments'
    | '/academic/profile'
    | '/academic/resources'
    | '/academic/services'
    | '/academic/store'
    | '/academic/support'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/requests'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tutors'
    | '/admin/users'
    | '/corporate/consulting'
    | '/corporate/notifications'
    | '/corporate/orders'
    | '/corporate/payments'
    | '/corporate/procurements'
    | '/corporate/profile'
    | '/corporate/resources'
    | '/corporate/services'
    | '/corporate/store'
    | '/corporate/support'
    | '/exam/notifications'
    | '/exam/orders'
    | '/exam/payments'
    | '/exam/profile'
    | '/exam/resources'
    | '/exam/services'
    | '/exam/store'
    | '/exam/support'
    | '/exam/tutoring'
    | '/admin/requests/consulting/$requestId'
    | '/admin/requests/procurement/$requestId'
    | '/admin/requests/tutor/$requestId'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/reset-password'
    | '/terms-of-service'
    | '/orders/$orderId'
    | '/payments/$paymentId'
    | '/support/$ticketId'
    | '/support/new'
    | '/academic/'
    | '/admin/'
    | '/corporate/'
    | '/exam/'
    | '/notifications/'
    | '/orders/'
    | '/payments/'
    | '/profile/'
    | '/resources/'
    | '/support/'
    | '/academic/checkout/$orderId'
    | '/academic/orders/$orderId'
    | '/academic/payments/$paymentId'
    | '/academic/services/$productId'
    | '/academic/store/$productId'
    | '/academic/support/$ticketId'
    | '/academic/support/new'
    | '/admin/orders/$orderId'
    | '/admin/payments/$paymentId'
    | '/admin/resources/$resourceId'
    | '/admin/resources/new'
    | '/admin/support/$ticketId'
    | '/admin/tutors/$tutorId'
    | '/admin/tutors/new'
    | '/admin/users/$userId'
    | '/corporate/checkout/$orderId'
    | '/corporate/orders/$orderId'
    | '/corporate/payments/$paymentId'
    | '/corporate/services/$productId'
    | '/corporate/store/$productId'
    | '/corporate/support/$ticketId'
    | '/corporate/support/new'
    | '/exam/checkout/$orderId'
    | '/exam/orders/$orderId'
    | '/exam/payments/$paymentId'
    | '/exam/services/$productId'
    | '/exam/store/$productId'
    | '/exam/support/$ticketId'
    | '/exam/support/new'
    | '/exam/tutoring/$requestId'
    | '/exam/tutoring/new'
    | '/academic/notifications/'
    | '/academic/orders/'
    | '/academic/payments/'
    | '/academic/profile/'
    | '/academic/resources/'
    | '/academic/services/'
    | '/academic/store/'
    | '/academic/support/'
    | '/admin/notifications/'
    | '/admin/orders/'
    | '/admin/payments/'
    | '/admin/requests/'
    | '/admin/resources/'
    | '/admin/settings/'
    | '/admin/support/'
    | '/admin/tutors/'
    | '/admin/users/'
    | '/corporate/consulting/'
    | '/corporate/notifications/'
    | '/corporate/orders/'
    | '/corporate/payments/'
    | '/corporate/procurements/'
    | '/corporate/profile/'
    | '/corporate/resources/'
    | '/corporate/services/'
    | '/corporate/store/'
    | '/corporate/support/'
    | '/exam/notifications/'
    | '/exam/orders/'
    | '/exam/payments/'
    | '/exam/profile/'
    | '/exam/resources/'
    | '/exam/services/'
    | '/exam/store/'
    | '/exam/support/'
    | '/exam/tutoring/'
    | '/admin/requests/consulting/$requestId'
    | '/admin/requests/procurement/$requestId'
    | '/admin/requests/tutor/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  PaymentsPaymentIdRoute: typeof PaymentsPaymentIdRoute
  SupportTicketIdRoute: typeof SupportTicketIdRoute
  SupportNewRoute: typeof SupportNewRoute
  AcademicIndexRoute: typeof AcademicIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CorporateIndexRoute: typeof CorporateIndexRoute
  ExamIndexRoute: typeof ExamIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  AcademicCheckoutOrderIdRoute: typeof AcademicCheckoutOrderIdRoute
  AcademicOrdersOrderIdRoute: typeof AcademicOrdersOrderIdRoute
  AcademicPaymentsPaymentIdRoute: typeof AcademicPaymentsPaymentIdRoute
  AcademicServicesProductIdRoute: typeof AcademicServicesProductIdRoute
  AcademicStoreProductIdRoute: typeof AcademicStoreProductIdRoute
  AcademicSupportTicketIdRoute: typeof AcademicSupportTicketIdRoute
  AcademicSupportNewRoute: typeof AcademicSupportNewRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminPaymentsPaymentIdRoute: typeof AdminPaymentsPaymentIdRoute
  AdminResourcesResourceIdRoute: typeof AdminResourcesResourceIdRoute
  AdminResourcesNewRoute: typeof AdminResourcesNewRoute
  AdminSupportTicketIdRoute: typeof AdminSupportTicketIdRoute
  AdminTutorsTutorIdRoute: typeof AdminTutorsTutorIdRoute
  AdminTutorsNewRoute: typeof AdminTutorsNewRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  CorporateCheckoutOrderIdRoute: typeof CorporateCheckoutOrderIdRoute
  CorporateOrdersOrderIdRoute: typeof CorporateOrdersOrderIdRoute
  CorporatePaymentsPaymentIdRoute: typeof CorporatePaymentsPaymentIdRoute
  CorporateServicesProductIdRoute: typeof CorporateServicesProductIdRoute
  CorporateStoreProductIdRoute: typeof CorporateStoreProductIdRoute
  CorporateSupportTicketIdRoute: typeof CorporateSupportTicketIdRoute
  CorporateSupportNewRoute: typeof CorporateSupportNewRoute
  ExamCheckoutOrderIdRoute: typeof ExamCheckoutOrderIdRoute
  ExamOrdersOrderIdRoute: typeof ExamOrdersOrderIdRoute
  ExamPaymentsPaymentIdRoute: typeof ExamPaymentsPaymentIdRoute
  ExamServicesProductIdRoute: typeof ExamServicesProductIdRoute
  ExamStoreProductIdRoute: typeof ExamStoreProductIdRoute
  ExamSupportTicketIdRoute: typeof ExamSupportTicketIdRoute
  ExamSupportNewRoute: typeof ExamSupportNewRoute
  ExamTutoringRequestIdRoute: typeof ExamTutoringRequestIdRoute
  ExamTutoringNewRoute: typeof ExamTutoringNewRoute
  AcademicNotificationsIndexRoute: typeof AcademicNotificationsIndexRoute
  AcademicOrdersIndexRoute: typeof AcademicOrdersIndexRoute
  AcademicPaymentsIndexRoute: typeof AcademicPaymentsIndexRoute
  AcademicProfileIndexRoute: typeof AcademicProfileIndexRoute
  AcademicResourcesIndexRoute: typeof AcademicResourcesIndexRoute
  AcademicServicesIndexRoute: typeof AcademicServicesIndexRoute
  AcademicStoreIndexRoute: typeof AcademicStoreIndexRoute
  AcademicSupportIndexRoute: typeof AcademicSupportIndexRoute
  AdminNotificationsIndexRoute: typeof AdminNotificationsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
  AdminResourcesIndexRoute: typeof AdminResourcesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminSupportIndexRoute: typeof AdminSupportIndexRoute
  AdminTutorsIndexRoute: typeof AdminTutorsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  CorporateConsultingIndexRoute: typeof CorporateConsultingIndexRoute
  CorporateNotificationsIndexRoute: typeof CorporateNotificationsIndexRoute
  CorporateOrdersIndexRoute: typeof CorporateOrdersIndexRoute
  CorporatePaymentsIndexRoute: typeof CorporatePaymentsIndexRoute
  CorporateProcurementsIndexRoute: typeof CorporateProcurementsIndexRoute
  CorporateProfileIndexRoute: typeof CorporateProfileIndexRoute
  CorporateResourcesIndexRoute: typeof CorporateResourcesIndexRoute
  CorporateServicesIndexRoute: typeof CorporateServicesIndexRoute
  CorporateStoreIndexRoute: typeof CorporateStoreIndexRoute
  CorporateSupportIndexRoute: typeof CorporateSupportIndexRoute
  ExamNotificationsIndexRoute: typeof ExamNotificationsIndexRoute
  ExamOrdersIndexRoute: typeof ExamOrdersIndexRoute
  ExamPaymentsIndexRoute: typeof ExamPaymentsIndexRoute
  ExamProfileIndexRoute: typeof ExamProfileIndexRoute
  ExamResourcesIndexRoute: typeof ExamResourcesIndexRoute
  ExamServicesIndexRoute: typeof ExamServicesIndexRoute
  ExamStoreIndexRoute: typeof ExamStoreIndexRoute
  ExamSupportIndexRoute: typeof ExamSupportIndexRoute
  ExamTutoringIndexRoute: typeof ExamTutoringIndexRoute
  AdminRequestsConsultingRequestIdRoute: typeof AdminRequestsConsultingRequestIdRoute
  AdminRequestsProcurementRequestIdRoute: typeof AdminRequestsProcurementRequestIdRoute
  AdminRequestsTutorRequestIdRoute: typeof AdminRequestsTutorRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/': {
      id: '/academic/'
      path: '/academic'
      fullPath: '/academic/'
      preLoaderRoute: typeof AcademicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/': {
      id: '/corporate/'
      path: '/corporate'
      fullPath: '/corporate/'
      preLoaderRoute: typeof CorporateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/': {
      id: '/exam/'
      path: '/exam'
      fullPath: '/exam/'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$paymentId': {
      id: '/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/payments/$paymentId'
      preLoaderRoute: typeof PaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$ticketId': {
      id: '/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof SupportTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/new': {
      id: '/support/new'
      path: '/support/new'
      fullPath: '/support/new'
      preLoaderRoute: typeof SupportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/checkout/$orderId': {
      id: '/academic/checkout/$orderId'
      path: '/academic/checkout/$orderId'
      fullPath: '/academic/checkout/$orderId'
      preLoaderRoute: typeof AcademicCheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/notifications/': {
      id: '/academic/notifications/'
      path: '/academic/notifications'
      fullPath: '/academic/notifications/'
      preLoaderRoute: typeof AcademicNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/orders/': {
      id: '/academic/orders/'
      path: '/academic/orders'
      fullPath: '/academic/orders/'
      preLoaderRoute: typeof AcademicOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/orders/$orderId': {
      id: '/academic/orders/$orderId'
      path: '/academic/orders/$orderId'
      fullPath: '/academic/orders/$orderId'
      preLoaderRoute: typeof AcademicOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/payments/': {
      id: '/academic/payments/'
      path: '/academic/payments'
      fullPath: '/academic/payments/'
      preLoaderRoute: typeof AcademicPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/payments/$paymentId': {
      id: '/academic/payments/$paymentId'
      path: '/academic/payments/$paymentId'
      fullPath: '/academic/payments/$paymentId'
      preLoaderRoute: typeof AcademicPaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/profile/': {
      id: '/academic/profile/'
      path: '/academic/profile'
      fullPath: '/academic/profile/'
      preLoaderRoute: typeof AcademicProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/resources/': {
      id: '/academic/resources/'
      path: '/academic/resources'
      fullPath: '/academic/resources/'
      preLoaderRoute: typeof AcademicResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/services/': {
      id: '/academic/services/'
      path: '/academic/services'
      fullPath: '/academic/services/'
      preLoaderRoute: typeof AcademicServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/services/$productId': {
      id: '/academic/services/$productId'
      path: '/academic/services/$productId'
      fullPath: '/academic/services/$productId'
      preLoaderRoute: typeof AcademicServicesProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/store/': {
      id: '/academic/store/'
      path: '/academic/store'
      fullPath: '/academic/store/'
      preLoaderRoute: typeof AcademicStoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/store/$productId': {
      id: '/academic/store/$productId'
      path: '/academic/store/$productId'
      fullPath: '/academic/store/$productId'
      preLoaderRoute: typeof AcademicStoreProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/support/': {
      id: '/academic/support/'
      path: '/academic/support'
      fullPath: '/academic/support/'
      preLoaderRoute: typeof AcademicSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/support/$ticketId': {
      id: '/academic/support/$ticketId'
      path: '/academic/support/$ticketId'
      fullPath: '/academic/support/$ticketId'
      preLoaderRoute: typeof AcademicSupportTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/support/new': {
      id: '/academic/support/new'
      path: '/academic/support/new'
      fullPath: '/academic/support/new'
      preLoaderRoute: typeof AcademicSupportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications/': {
      id: '/admin/notifications/'
      path: '/admin/notifications'
      fullPath: '/admin/notifications/'
      preLoaderRoute: typeof AdminNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/admin/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/$paymentId': {
      id: '/admin/payments/$paymentId'
      path: '/admin/payments/$paymentId'
      fullPath: '/admin/payments/$paymentId'
      preLoaderRoute: typeof AdminPaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/admin/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resources/': {
      id: '/admin/resources/'
      path: '/admin/resources'
      fullPath: '/admin/resources/'
      preLoaderRoute: typeof AdminResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resources/$resourceId': {
      id: '/admin/resources/$resourceId'
      path: '/admin/resources/$resourceId'
      fullPath: '/admin/resources/$resourceId'
      preLoaderRoute: typeof AdminResourcesResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resources/new': {
      id: '/admin/resources/new'
      path: '/admin/resources/new'
      fullPath: '/admin/resources/new'
      preLoaderRoute: typeof AdminResourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support/': {
      id: '/admin/support/'
      path: '/admin/support'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AdminSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support/$ticketId': {
      id: '/admin/support/$ticketId'
      path: '/admin/support/$ticketId'
      fullPath: '/admin/support/$ticketId'
      preLoaderRoute: typeof AdminSupportTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tutors/': {
      id: '/admin/tutors/'
      path: '/admin/tutors'
      fullPath: '/admin/tutors/'
      preLoaderRoute: typeof AdminTutorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tutors/$tutorId': {
      id: '/admin/tutors/$tutorId'
      path: '/admin/tutors/$tutorId'
      fullPath: '/admin/tutors/$tutorId'
      preLoaderRoute: typeof AdminTutorsTutorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tutors/new': {
      id: '/admin/tutors/new'
      path: '/admin/tutors/new'
      fullPath: '/admin/tutors/new'
      preLoaderRoute: typeof AdminTutorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/checkout/$orderId': {
      id: '/corporate/checkout/$orderId'
      path: '/corporate/checkout/$orderId'
      fullPath: '/corporate/checkout/$orderId'
      preLoaderRoute: typeof CorporateCheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/consulting/': {
      id: '/corporate/consulting/'
      path: '/corporate/consulting'
      fullPath: '/corporate/consulting/'
      preLoaderRoute: typeof CorporateConsultingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/notifications/': {
      id: '/corporate/notifications/'
      path: '/corporate/notifications'
      fullPath: '/corporate/notifications/'
      preLoaderRoute: typeof CorporateNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/orders/': {
      id: '/corporate/orders/'
      path: '/corporate/orders'
      fullPath: '/corporate/orders/'
      preLoaderRoute: typeof CorporateOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/orders/$orderId': {
      id: '/corporate/orders/$orderId'
      path: '/corporate/orders/$orderId'
      fullPath: '/corporate/orders/$orderId'
      preLoaderRoute: typeof CorporateOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/payments/': {
      id: '/corporate/payments/'
      path: '/corporate/payments'
      fullPath: '/corporate/payments/'
      preLoaderRoute: typeof CorporatePaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/payments/$paymentId': {
      id: '/corporate/payments/$paymentId'
      path: '/corporate/payments/$paymentId'
      fullPath: '/corporate/payments/$paymentId'
      preLoaderRoute: typeof CorporatePaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/procurements/': {
      id: '/corporate/procurements/'
      path: '/corporate/procurements'
      fullPath: '/corporate/procurements/'
      preLoaderRoute: typeof CorporateProcurementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/profile/': {
      id: '/corporate/profile/'
      path: '/corporate/profile'
      fullPath: '/corporate/profile/'
      preLoaderRoute: typeof CorporateProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/resources/': {
      id: '/corporate/resources/'
      path: '/corporate/resources'
      fullPath: '/corporate/resources/'
      preLoaderRoute: typeof CorporateResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/services/': {
      id: '/corporate/services/'
      path: '/corporate/services'
      fullPath: '/corporate/services/'
      preLoaderRoute: typeof CorporateServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/services/$productId': {
      id: '/corporate/services/$productId'
      path: '/corporate/services/$productId'
      fullPath: '/corporate/services/$productId'
      preLoaderRoute: typeof CorporateServicesProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/store/': {
      id: '/corporate/store/'
      path: '/corporate/store'
      fullPath: '/corporate/store/'
      preLoaderRoute: typeof CorporateStoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/store/$productId': {
      id: '/corporate/store/$productId'
      path: '/corporate/store/$productId'
      fullPath: '/corporate/store/$productId'
      preLoaderRoute: typeof CorporateStoreProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/support/': {
      id: '/corporate/support/'
      path: '/corporate/support'
      fullPath: '/corporate/support/'
      preLoaderRoute: typeof CorporateSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/support/$ticketId': {
      id: '/corporate/support/$ticketId'
      path: '/corporate/support/$ticketId'
      fullPath: '/corporate/support/$ticketId'
      preLoaderRoute: typeof CorporateSupportTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/support/new': {
      id: '/corporate/support/new'
      path: '/corporate/support/new'
      fullPath: '/corporate/support/new'
      preLoaderRoute: typeof CorporateSupportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/checkout/$orderId': {
      id: '/exam/checkout/$orderId'
      path: '/exam/checkout/$orderId'
      fullPath: '/exam/checkout/$orderId'
      preLoaderRoute: typeof ExamCheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/notifications/': {
      id: '/exam/notifications/'
      path: '/exam/notifications'
      fullPath: '/exam/notifications/'
      preLoaderRoute: typeof ExamNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/orders/': {
      id: '/exam/orders/'
      path: '/exam/orders'
      fullPath: '/exam/orders/'
      preLoaderRoute: typeof ExamOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/orders/$orderId': {
      id: '/exam/orders/$orderId'
      path: '/exam/orders/$orderId'
      fullPath: '/exam/orders/$orderId'
      preLoaderRoute: typeof ExamOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/payments/': {
      id: '/exam/payments/'
      path: '/exam/payments'
      fullPath: '/exam/payments/'
      preLoaderRoute: typeof ExamPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/payments/$paymentId': {
      id: '/exam/payments/$paymentId'
      path: '/exam/payments/$paymentId'
      fullPath: '/exam/payments/$paymentId'
      preLoaderRoute: typeof ExamPaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/profile/': {
      id: '/exam/profile/'
      path: '/exam/profile'
      fullPath: '/exam/profile/'
      preLoaderRoute: typeof ExamProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/resources/': {
      id: '/exam/resources/'
      path: '/exam/resources'
      fullPath: '/exam/resources/'
      preLoaderRoute: typeof ExamResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/services/': {
      id: '/exam/services/'
      path: '/exam/services'
      fullPath: '/exam/services/'
      preLoaderRoute: typeof ExamServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/services/$productId': {
      id: '/exam/services/$productId'
      path: '/exam/services/$productId'
      fullPath: '/exam/services/$productId'
      preLoaderRoute: typeof ExamServicesProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/store/': {
      id: '/exam/store/'
      path: '/exam/store'
      fullPath: '/exam/store/'
      preLoaderRoute: typeof ExamStoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/store/$productId': {
      id: '/exam/store/$productId'
      path: '/exam/store/$productId'
      fullPath: '/exam/store/$productId'
      preLoaderRoute: typeof ExamStoreProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/support/': {
      id: '/exam/support/'
      path: '/exam/support'
      fullPath: '/exam/support/'
      preLoaderRoute: typeof ExamSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/support/$ticketId': {
      id: '/exam/support/$ticketId'
      path: '/exam/support/$ticketId'
      fullPath: '/exam/support/$ticketId'
      preLoaderRoute: typeof ExamSupportTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/support/new': {
      id: '/exam/support/new'
      path: '/exam/support/new'
      fullPath: '/exam/support/new'
      preLoaderRoute: typeof ExamSupportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/tutoring/': {
      id: '/exam/tutoring/'
      path: '/exam/tutoring'
      fullPath: '/exam/tutoring/'
      preLoaderRoute: typeof ExamTutoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/tutoring/$requestId': {
      id: '/exam/tutoring/$requestId'
      path: '/exam/tutoring/$requestId'
      fullPath: '/exam/tutoring/$requestId'
      preLoaderRoute: typeof ExamTutoringRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/tutoring/new': {
      id: '/exam/tutoring/new'
      path: '/exam/tutoring/new'
      fullPath: '/exam/tutoring/new'
      preLoaderRoute: typeof ExamTutoringNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/consulting/$requestId': {
      id: '/admin/requests/consulting/$requestId'
      path: '/admin/requests/consulting/$requestId'
      fullPath: '/admin/requests/consulting/$requestId'
      preLoaderRoute: typeof AdminRequestsConsultingRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/procurement/$requestId': {
      id: '/admin/requests/procurement/$requestId'
      path: '/admin/requests/procurement/$requestId'
      fullPath: '/admin/requests/procurement/$requestId'
      preLoaderRoute: typeof AdminRequestsProcurementRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/tutor/$requestId': {
      id: '/admin/requests/tutor/$requestId'
      path: '/admin/requests/tutor/$requestId'
      fullPath: '/admin/requests/tutor/$requestId'
      preLoaderRoute: typeof AdminRequestsTutorRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  PaymentsPaymentIdRoute: PaymentsPaymentIdRoute,
  SupportTicketIdRoute: SupportTicketIdRoute,
  SupportNewRoute: SupportNewRoute,
  AcademicIndexRoute: AcademicIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  CorporateIndexRoute: CorporateIndexRoute,
  ExamIndexRoute: ExamIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  AcademicCheckoutOrderIdRoute: AcademicCheckoutOrderIdRoute,
  AcademicOrdersOrderIdRoute: AcademicOrdersOrderIdRoute,
  AcademicPaymentsPaymentIdRoute: AcademicPaymentsPaymentIdRoute,
  AcademicServicesProductIdRoute: AcademicServicesProductIdRoute,
  AcademicStoreProductIdRoute: AcademicStoreProductIdRoute,
  AcademicSupportTicketIdRoute: AcademicSupportTicketIdRoute,
  AcademicSupportNewRoute: AcademicSupportNewRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminPaymentsPaymentIdRoute: AdminPaymentsPaymentIdRoute,
  AdminResourcesResourceIdRoute: AdminResourcesResourceIdRoute,
  AdminResourcesNewRoute: AdminResourcesNewRoute,
  AdminSupportTicketIdRoute: AdminSupportTicketIdRoute,
  AdminTutorsTutorIdRoute: AdminTutorsTutorIdRoute,
  AdminTutorsNewRoute: AdminTutorsNewRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  CorporateCheckoutOrderIdRoute: CorporateCheckoutOrderIdRoute,
  CorporateOrdersOrderIdRoute: CorporateOrdersOrderIdRoute,
  CorporatePaymentsPaymentIdRoute: CorporatePaymentsPaymentIdRoute,
  CorporateServicesProductIdRoute: CorporateServicesProductIdRoute,
  CorporateStoreProductIdRoute: CorporateStoreProductIdRoute,
  CorporateSupportTicketIdRoute: CorporateSupportTicketIdRoute,
  CorporateSupportNewRoute: CorporateSupportNewRoute,
  ExamCheckoutOrderIdRoute: ExamCheckoutOrderIdRoute,
  ExamOrdersOrderIdRoute: ExamOrdersOrderIdRoute,
  ExamPaymentsPaymentIdRoute: ExamPaymentsPaymentIdRoute,
  ExamServicesProductIdRoute: ExamServicesProductIdRoute,
  ExamStoreProductIdRoute: ExamStoreProductIdRoute,
  ExamSupportTicketIdRoute: ExamSupportTicketIdRoute,
  ExamSupportNewRoute: ExamSupportNewRoute,
  ExamTutoringRequestIdRoute: ExamTutoringRequestIdRoute,
  ExamTutoringNewRoute: ExamTutoringNewRoute,
  AcademicNotificationsIndexRoute: AcademicNotificationsIndexRoute,
  AcademicOrdersIndexRoute: AcademicOrdersIndexRoute,
  AcademicPaymentsIndexRoute: AcademicPaymentsIndexRoute,
  AcademicProfileIndexRoute: AcademicProfileIndexRoute,
  AcademicResourcesIndexRoute: AcademicResourcesIndexRoute,
  AcademicServicesIndexRoute: AcademicServicesIndexRoute,
  AcademicStoreIndexRoute: AcademicStoreIndexRoute,
  AcademicSupportIndexRoute: AcademicSupportIndexRoute,
  AdminNotificationsIndexRoute: AdminNotificationsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
  AdminResourcesIndexRoute: AdminResourcesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminSupportIndexRoute: AdminSupportIndexRoute,
  AdminTutorsIndexRoute: AdminTutorsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  CorporateConsultingIndexRoute: CorporateConsultingIndexRoute,
  CorporateNotificationsIndexRoute: CorporateNotificationsIndexRoute,
  CorporateOrdersIndexRoute: CorporateOrdersIndexRoute,
  CorporatePaymentsIndexRoute: CorporatePaymentsIndexRoute,
  CorporateProcurementsIndexRoute: CorporateProcurementsIndexRoute,
  CorporateProfileIndexRoute: CorporateProfileIndexRoute,
  CorporateResourcesIndexRoute: CorporateResourcesIndexRoute,
  CorporateServicesIndexRoute: CorporateServicesIndexRoute,
  CorporateStoreIndexRoute: CorporateStoreIndexRoute,
  CorporateSupportIndexRoute: CorporateSupportIndexRoute,
  ExamNotificationsIndexRoute: ExamNotificationsIndexRoute,
  ExamOrdersIndexRoute: ExamOrdersIndexRoute,
  ExamPaymentsIndexRoute: ExamPaymentsIndexRoute,
  ExamProfileIndexRoute: ExamProfileIndexRoute,
  ExamResourcesIndexRoute: ExamResourcesIndexRoute,
  ExamServicesIndexRoute: ExamServicesIndexRoute,
  ExamStoreIndexRoute: ExamStoreIndexRoute,
  ExamSupportIndexRoute: ExamSupportIndexRoute,
  ExamTutoringIndexRoute: ExamTutoringIndexRoute,
  AdminRequestsConsultingRequestIdRoute: AdminRequestsConsultingRequestIdRoute,
  AdminRequestsProcurementRequestIdRoute:
    AdminRequestsProcurementRequestIdRoute,
  AdminRequestsTutorRequestIdRoute: AdminRequestsTutorRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
